default: &default
  adapter: postgis
  schema_search_path: "public,postgis"
  encoding: unicode
  pool: 5
  username: geo_rails_test
  password: geo_rails_test

development:
  <<: *default
  database: geo_rails_test_development
<<<<<<< HEAD
  # database: geo_rails_test_production
=======
  #database: geo_rails_test_production
>>>>>>> 6e69fe59f79ffe6f8775ba82a86fb9e303f445b1
  host: 60.10.135.153
  port: 5432

test:
  <<: *default
  database: geo_rails_test_test
  # host: 60.10.135.153
  # port: 5432


production:
    #url: <%= ENV['DATABASE_URL'] %>
  <<: *default
  database: geo_rails_test_production
  host: 60.10.135.153
  port: 5432
  #username: geo_rails_test
  #password: <%= ENV['GEO_RAILS_TEST_DATABASE_PASSWORD'] %>
